var arr=[
		1,"Primera Regi\u00F3n",[
			1,"Alto Hospicio",[],
			2,"Cami\u00F1a",[],
			3,"Colchane",[],
			4,"Huara",[],
			5,"Iquique",[],
			6,"Pica",[],
			7,"Pozo al Monte",[],
		],

		2,"Segunda Regi\u00F3n",[
			1,"Antofagasta",[],
			2,"Calama",[],
			3,"Mar\u00EDa Elena",[],
			4,"Mejillones",[],
			5,"Ollag\u00FCe",[],
			6,"San Pedro de Atacama",[],
			7,"Sierra Gorda",[],
			8,"Taltal",[],
			9,"Tocopilla",[],
		],

		3,"Tercera Regi\u00F3n",[
			1,"Alto del Carmen",[],
			2,"Caldera",[],
			3,"Cha\u00F1aral",[],
			4,"Copiap\u00F3",[],
			5,"Diego de Almagro",[],
			6,"Freirina",[],
			7,"Huasco",[],
			8,"Tierra Amarilla",[],
			9,"Vallenar",[],
		],

		4,"Cuarta Regi\u00F3n",[
			1,"Andacollo",[],
			2,"Canela",[],
			3,"Combarbal\u00E1",[],
			4,"Coquimbo",[],			
			5,"Illapel",[],
			6,"La Serena",[],
			7,"La Higuera",[],
			8,"Los Vilos",[],
			9,"Monte Patria",[],
			10,"Ovalle",[],
			11,"Paiguano",[],
			12,"Punitaqui",[],
			13,"R\u00EDo Hurtado",[],
			14,"Salamanca",[],
			15,"Vicu\u00F1a",[],
		],

		5,"Quinta Regi\u00F3n",[
			1,"Algarrobo",[],
			2,"Cabildo",[],
			3,"Cartagena",[],
			4,"Casablanca",[],
			5,"Catemu",[],
			6,"Conc\u00F3n",[],
			7,"El Quisco",[],
			8,"El Tabo",[],
			9,"Hijuelas",[],
			10,"Isla de Pascua",[],
			11,"Juan Fern\u00E1ndez",[],
			12,"La Calera",[],
			13,"La Cruz",[],
			14,"La Ligua",[],
			15,"Limache",[],
			16,"Llaillay",[],
			17,"Los Andes",[],
			18,"Nogales",[],
			19,"Olmu\u00E9",[],
			20,"Panquehue",[],
			21,"Papudo",[],
			22,"Petorca",[],
			23,"Putaendo",[],
			24,"Puchuncav\u00ED",[],
			25,"Quillota",[],
			26,"Quilpu\u00E9",[],
			27,"Quintero",[],
			28,"San Antonio",[],
			29,"San Felipe",[],
			30,"Santa Mar\u00EDa",[],
			31,"Santo Domingo",[],
			32,"Valpara\u00EDso",[],
			33,"Villa Alemana",[],
			34,"Vi\u00F1a del Mar",[],
			35,"Zapallar",[],
		],

		6,"Sexta Regi\u00F3n",[
			1,"Ch\u00E9pica",[],		
			2,"Chimbarongo",[],
			3,"Codegua",[],
			4,"Coinco",[],
			5,"Coltauco",[],
			6,"Do\u00F1ihue",[],
			7,"Graneros",[],
			8,"La Estrella",[],
			9,"Las Cabras",[],
			10,"Litueche",[],
			11,"Lolol",[],
			12,"Machal\u00ED",[],
			13,"Malloa",[],
			14,"Marchihue",[],
			15,"Mostazal",[],
			16,"Nancagua",[],
			17,"Navidad",[],
			18,"Olivar",[],
			19,"Palmilla",[],
			20,"Paredones",[],
			21,"Peralillo",[],
			22,"Peumo",[],
			23,"Pichidegua",[],
			24,"Pichilemu",[],
			25,"Placilla",[],
			26,"Pumanque",[],
			27,"Quinta de Tilcoco",[],
			28,"Rancagua",[],
			29,"Rengo",[],
			30,"Requinoa",[],
			31,"San Fernando",[],
			32,"San Vicente",[],
			33,"Santa Cruz",[],
		],

		7,"Septima Regi\u00F3n",[
			1,"Cauquenes",[],
			2,"Pelluhue",[],
			3,"Chanco",[],
			4,"Curic\u00F3",[],
			5,"Teno",[],
			6,"Romeral",[],
			7,"Molina",[],
			8,"Sagrada Familia",[],
			9,"Huala\u00F1\u00E9",[],
			10,"Licant\u00E9n",[],
			11,"Vichuqu\u00E9n",[],
			12,"Rauco",[],
			13,"Linares",[],
			14,"Yerbas Buenas",[],
			15,"Colb\u00FAn",[],
			16,"Longav\u00ED",[],
			17,"Parral",[],
			18,"Retiro",[],
			19,"Villa Alegre",[],
			20,"San Javier",[],
			21,"Talca",[],
			22,"Pelarco",[],
			23,"R\u00EDo Claro",[],
			24,"San Clemente",[],
			25,"Maule",[],
			26,"Empedrado",[],
			27,"Pencahue",[],
			28,"Constituci\u00F3n",[],
			29,"Curepto",[],
			30,"San Rafael",[],
		],
		
		8,"Octava Regi\u00F3n",[
			1,"Alto B\u00EDo B\u00EDo",[],
			2,"Antuco",[],
			3,"Arauco",[],
			4,"Bulnes",[],
			5,"Cabrero",[],
			6,"Ca\u00F1ete",[],
			7,"Chill\u00E1n",[],
			8,"Chill\u00E1n Viejo",[],
			9,"Cobquecura",[],
			10,"Coelemu",[],
			11,"Coihueco",[],
			12,"Contulmo",[],
			13,"Concepci\u00F3n",[],
			14,"Coronel",[],
			15,"Curanilahue",[],
			16,"El Carmen",[],
			17,"Florida",[],
			18,"Hualqui",[],
			19,"Laja",[],
			20,"Lebu",[],
			21,"Los Ángeles",[],
			22,"Lota",[],
			23,"Mulch\u00E9n",[],
			24,"Nacimiento",[],
			25,"Negrete",[],
			26,"Ninhue",[],
			27,"\u00D1iqu\u00E9n",[],
			28,"Pemuco",[],
			29,"Penco",[],
			30,"Pinto",[],
			31,"Portezuelo",[],
			32,"Quilaco",[],
			33,"Quilleco",[],
			34,"Quill\u00F3n",[],
			35,"Quirihue",[],
			36,"Ranquil",[],
			37,"San Carlos",[],
			38,"San Fabi\u00E1n",[],
			39,"San Ignacio",[],
			40,"San Nicol\u00E1s",[],
			41,"San Pedro de la Paz",[],
			42,"San Rosendo",[],
			43,"Santa B\u00E1rbara",[],
			44,"Santa Juana",[],
			45,"Talcahuano",[],
			46,"Tir\u00FAa",[],
			47,"Tom\u00E9",[],
			48,"Treguaco",[],
			49,"Tucapel",[],
			50,"Yungay",[],
		],

		9,"Novena  Regi\u00F3n",[
			1,"Angol",[],
			2,"Carahue",[],
			3,"Cholchol",[],
			4,"Collipulli",[],
			5,"Cunco",[],
			5,"Curacaut\u00EDn",[],
			7,"Currarrehue",[],
			8,"Ercilla",[],
			9,"Freire",[],
			10,"Galvarino",[],
			11,"Gorbea",[],
			12,"Lautaro",[],
			13,"Loncoche",[],
			14,"Lonquimay",[],
			15,"Los Sauces",[],
			16,"Lumaco",[],
			17,"Melipeuco",[],
			18,"Nueva Imperial",[],
			19,"Padre Las Casas",[],
			20,"Perquenco",[],
			21,"Pitrufqu\u00E9n",[],
			22,"Puc\u00F3n",[],
			23,"Pur\u00E9n",[],
			24,"Renaico",[],
			25,"Saavedra",[],
			26,"Temuco",[],
			27,"Teodoro Schmidt",[],
			28,"Tolt\u00E9n",[],
			29,"Traigu\u00E9n",[],
			30,"Victoria",[],
			31,"Vilc\u00FAn",[],
			32,"Villarrica",[],
		],

		10,"D\u00E9cima Regi\u00F3n",[
			1,"Ancud",[],
			2,"Calbuco",[],
			3,"Castro",[],
			4,"Chait\u00E9n",[],
			5,"Chonchi",[],
			6,"Cocham\u00F3",[],
			7,"Curaco de V\u00E9lez",[],
			8,"Dalcahue",[],
			9,"Fresia",[],
			10,"Frutillar",[],
			11,"Futaleuf\u00FA",[],
			12,"Hualaihu\u00E9",[],
			13,"Llanquihue",[],
			14,"Los Muermos",[],
			15,"Maull\u00EDn",[],
			16,"Osorno",[],
			17,"Puerto Montt",[],
			18,"Puerto Octay",[],
			19,"Puerto Varas",[],
			20,"Palena",[],
			21,"Puqueld\u00F3n",[],
			22,"Purranque",[],
			23,"Puyehue",[],
			24,"Quemchi",[],
			25,"Queil\u00E9n",[],
			26,"Quell\u00F3n",[],
			27,"Quinchao",[],
			28,"R\u00EDo Negro",[],
			29,"San Juan de la Costa",[],
			30,"San Pablo",[],
		],

		11,"Decimoprimera Regi\u00F3n",[
			1,"Ays\u00E9n",[],
			2,"Chile Chico",[],
			3,"Cisnes",[],
			4,"Cochrane",[],
			5,"Coyhaique",[],
			6,"Guaitecas",[],
			7,"Lago Verde", [],
			8,"O'Higgins",[],
			9,"R\u00EDo Ib\u00E1\u00F1ez",[],
			10,"Tortel",[],
		],

		12,"Decimosegunda Regi\u00F3n",[
			1,"Ant\u00E1rtica",[],
			2,"Cabo de Hornos",[],
			3,"Laguna Blanca",[],
			4,"Natales",[],
			5,"Porvenir",[],
			6,"Primavera",[],
			7,"Punta Arenas",[],
			8,"R\u00EDo Verde",[],
			9,"San Gregorio",[],
			10,"Tierra del fuego",[],
			11,"Timaukel",[],
			12,"Torres del Paine",[],
		],
		
		14,"Decimocuarta Regi\u00F3n",[
			1,"Corral",[],
			2,"Futrono",[],
			3,"La Uni\u00F3n",[],
			4,"Lago Ranco",[],
			5,"Lanco",[],
			6,"Los Lagos",[],
			7,"M\u00E1fil",[],
			8,"Mariquina",[],
			9,"Paillaco",[],
			10,"Panguipulli",[],
			11,"R\u00EDo Bueno",[],
			12,"Valdivia",[],
		],
		
		15,"D\u00E9cimoquinta Regi\u00F3n",[
			1,"Arica",[],
			2,"Camarones",[],
			3,"General Lagos",[],
			4,"Putre",[],
		],

		13,"Regi\u00F3n Metropolitana",[
				1,"Alhu\u00E9",[],
				2,"Batuco",[],
				3,"Buin",[],
				4,"Caleu",[],
				5,"Champa",[],
				6,"Codigua",[],
				7,"Colina",[],
				8,"Curacav\u00ED",[],
				9,"El Array\u00E1n",[],
				10,"El Bollenar",[],
				11,"El Canelo",[],
				12,"El Monte",[],
				13,"El Paico",[],
				14,"El Romeral",[],
				15,"El Volc\u00E1n",[],
				16,"Hospital",[],
				17,"Isla de Maipo",[],
				18,"La Obra",[],
				19,"Lampa",[],
				20,"Linderos",[],
				21,"Maipo",[],
				22,"Mallarauco",[],
				23,"Malloco",[],
				24,"Mar\u00EDa Pinto",[],
				25,"Melipilla",[],
				26,"Melocot\u00F3n",[],
				27,"Montenegro",[],
				28,"Padre Hurtado",[],
				29,"Paine",[],
				30,"Pe\u00F1aflor",[],
				31,"Polpaico",[],
				32,"Pomaire",[],
				33,"Puangue",[],
				34,"Puangue Alto",[],
				36,"Rungue",[],
				37,"San Alfonso",[],
				38,"San Gabriel",[],
				39,"San Jos\u00E9 (Melipilla)",[],
				40,"San Jos\u00E9 de Maipo",[],
				41,"San Pedro (Melipilla)",[],
				42,"Santa Ana",[],
				43,"Santiago",[
						1,"Cerrillos",
						2,"Cerro Navia",
						3,"Conchal\u00ED",
						4,"El Bosque",
						5,"Estaci\u00F3n Central",
						6,"Huechuraba",
						7,"Independencia",
						8,"La Cisterna",
						9,"La Florida",
						10,"La Granja",
						11,"La Pintana",
						12,"La Reina",
						13,"Las Condes",
						14,"Lo Barnechea",
						15,"Lo Espejo",
						16,"Lo Prado",
						17,"Macul",
						18,"Maip\u00FA",
						19,"\u00D1u\u00F1oa",
						20,"Pedro Aguirre Cerda",
						21,"Pe\u00F1alol\u00E9n",
						22,"Providencia",
						23,"Pudahuel",
						24,"Puente Alto",
						25,"Quilicura",
						26,"Quinta Normal",
						27,"Recoleta",
						28,"Renca",
						29,"San Bernardo",
						30,"San Joaqu\u00EDn",
						31,"San Miguel",
						32,"San Ram\u00F3n",
						33,"Santiago Centro",
						34,"Vitacura", 
				   ],
				44,"Talagante",[],
				45,"Tiltil",[],
				46,"Valdivia de Paine",[],
		],
];