
package com.epcs.provision.suscripcion;

import javax.xml.ws.WebFault;
import com.epcs.provision.suscripcion.types.ListarBolsasActivasServiceFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "listarBolsasActivasServiceFaultDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
public class ListarBolsasActivasServiceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ListarBolsasActivasServiceFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ListarBolsasActivasServiceFaultMessage(String message, ListarBolsasActivasServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ListarBolsasActivasServiceFaultMessage(String message, ListarBolsasActivasServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epcs.provision.suscripcion.types.ListarBolsasActivasServiceFaultType
     */
    public ListarBolsasActivasServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
