
package com.epcs.billing.bolsa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BillingBolsaService", targetNamespace = "http://www.epcs.com/billing/bolsa", wsdlLocation = "BillingBolsaService.wsdl")
public class BillingBolsaService_Service
    extends Service
{

    private final static URL BILLINGBOLSASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epcs.billing.bolsa.BillingBolsaService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epcs.billing.bolsa.BillingBolsaService_Service.class.getResource(".");
            url = new URL(baseUrl, "BillingBolsaService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'BillingBolsaService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILLINGBOLSASERVICE_WSDL_LOCATION = url;
    }

    public BillingBolsaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingBolsaService_Service() {
        super(BILLINGBOLSASERVICE_WSDL_LOCATION, new QName("http://www.epcs.com/billing/bolsa", "BillingBolsaService"));
    }

    /**
     * 
     * @return
     *     returns BillingBolsaService
     */
    @WebEndpoint(name = "BillingBolsaServicePort")
    public BillingBolsaService getBillingBolsaServicePort() {
        return super.getPort(new QName("http://www.epcs.com/billing/bolsa", "BillingBolsaServicePort"), BillingBolsaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingBolsaService
     */
    @WebEndpoint(name = "BillingBolsaServicePort")
    public BillingBolsaService getBillingBolsaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epcs.com/billing/bolsa", "BillingBolsaServicePort"), BillingBolsaService.class, features);
    }

}
