
package com.epcs.provision.suscripcion;

import javax.xml.ws.WebFault;
import com.epcs.provision.suscripcion.types.ValidacionCompraServiceFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "validacionCompraServiceFaultDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
public class ValidacionCompraServiceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidacionCompraServiceFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ValidacionCompraServiceFaultMessage(String message, ValidacionCompraServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ValidacionCompraServiceFaultMessage(String message, ValidacionCompraServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epcs.provision.suscripcion.types.ValidacionCompraServiceFaultType
     */
    public ValidacionCompraServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
