
package com.epcs.cliente.orden;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClienteOrdenService", targetNamespace = "http://www.epcs.com/cliente/orden", wsdlLocation = "ClienteOrdenService.wsdl")
public class ClienteOrdenService_Service
    extends Service
{

    private final static URL CLIENTEORDENSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epcs.cliente.orden.ClienteOrdenService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epcs.cliente.orden.ClienteOrdenService_Service.class.getResource(".");
            url = new URL(baseUrl, "ClienteOrdenService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'ClienteOrdenService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CLIENTEORDENSERVICE_WSDL_LOCATION = url;
    }

    public ClienteOrdenService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteOrdenService_Service() {
        super(CLIENTEORDENSERVICE_WSDL_LOCATION, new QName("http://www.epcs.com/cliente/orden", "ClienteOrdenService"));
    }

    /**
     * 
     * @return
     *     returns ClienteOrdenService
     */
    @WebEndpoint(name = "ClienteOrdenServicePort")
    public ClienteOrdenService getClienteOrdenServicePort() {
        return super.getPort(new QName("http://www.epcs.com/cliente/orden", "ClienteOrdenServicePort"), ClienteOrdenService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteOrdenService
     */
    @WebEndpoint(name = "ClienteOrdenServicePort")
    public ClienteOrdenService getClienteOrdenServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epcs.com/cliente/orden", "ClienteOrdenServicePort"), ClienteOrdenService.class, features);
    }

}
