
package com.epcs.billing.balance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.billing.balance.types.ConsultarDetalleFacturaType;
import com.epcs.billing.balance.types.ConsultarEstadoFacturaType;
import com.epcs.billing.balance.types.ConsultarFacturacionFullType;
import com.epcs.billing.balance.types.ConsultarFacturacionSSCCType;
import com.epcs.billing.balance.types.ConsultarFacturasImpagasType;
import com.epcs.billing.balance.types.ConsultarResumenFacturacionType;
import com.epcs.billing.balance.types.ResultadoConsultarDetalleFacturaType;
import com.epcs.billing.balance.types.ResultadoConsultarEstadoFacturaType;
import com.epcs.billing.balance.types.ResultadoConsultarFacturacionFullType;
import com.epcs.billing.balance.types.ResultadoConsultarFacturacionSSCCType;
import com.epcs.billing.balance.types.ResultadoConsultarFacturasImpagasType;
import com.epcs.billing.balance.types.ResultadoConsultarResumenFacturacionType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BillingBalanceService", targetNamespace = "http://www.epcs.com/billing/balance")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.billing.balance.ObjectFactory.class,
    com.epcs.billing.balance.types.ObjectFactory.class
})
public interface BillingBalanceService {


    /**
     * 
     * @param consultarResumenFacturacion
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarResumenFacturacionType
     */
    @WebMethod(operationName = "ConsultarResumenFacturacion", action = "http://www.epcs.com/billing/balance/ConsultarResumenFacturacion")
    @WebResult(name = "ResultadoConsultarResumenFacturacionDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarResumenFacturacion")
    public ResultadoConsultarResumenFacturacionType consultarResumenFacturacion(
        @WebParam(name = "ConsultarResumenFacturacionDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarResumenFacturacion")
        ConsultarResumenFacturacionType consultarResumenFacturacion);

    /**
     * 
     * @param consultarFacturacionSSCC
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarFacturacionSSCCType
     */
    @WebMethod(operationName = "ConsultarFacturacionSSCC", action = "http://www.epcs.com/billing/balance/ConsultarFacturacionSSCC")
    @WebResult(name = "ResultadoConsultarFacturacionSSCCDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarFacturacionSSCC")
    public ResultadoConsultarFacturacionSSCCType consultarFacturacionSSCC(
        @WebParam(name = "ConsultarFacturacionSSCCDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarFacturacionSSCC")
        ConsultarFacturacionSSCCType consultarFacturacionSSCC);

    /**
     * 
     * @param consultarEstadoFactura
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarEstadoFacturaType
     */
    @WebMethod(operationName = "ConsultarEstadoFactura", action = "http://www.epcs.com/billing/balance/ConsultarEstadoFactura")
    @WebResult(name = "ResultadoConsultarEstadoFacturaDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarEstadoFactura")
    public ResultadoConsultarEstadoFacturaType consultarEstadoFactura(
        @WebParam(name = "ConsultarEstadoFacturaDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarEstadoFactura")
        ConsultarEstadoFacturaType consultarEstadoFactura);

    /**
     * 
     * @param consultarFacturacionFull
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarFacturacionFullType
     */
    @WebMethod(operationName = "ConsultarFacturacionFull", action = "http://www.epcs.com/billing/balance/ConsultarFacturacionFull")
    @WebResult(name = "ResultadoConsultarFacturacionFullDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarFacturacionFull")
    public ResultadoConsultarFacturacionFullType consultarFacturacionFull(
        @WebParam(name = "ConsultarFacturacionFullDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarFacturacionFull")
        ConsultarFacturacionFullType consultarFacturacionFull);

    /**
     * 
     * @param consultarDetalleFactura
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarDetalleFacturaType
     */
    @WebMethod(operationName = "ConsultarDetalleFactura", action = "http://www.epcs.com/billing/balance/ConsultarDetalleFactura")
    @WebResult(name = "ResultadoConsultarDetalleFacturaDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarDetalleFactura")
    public ResultadoConsultarDetalleFacturaType consultarDetalleFactura(
        @WebParam(name = "ConsultarDetalleFacturaDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarDetalleFactura")
        ConsultarDetalleFacturaType consultarDetalleFactura);

    /**
     * 
     * @param consultarFacturasImpagas
     * @return
     *     returns com.epcs.billing.balance.types.ResultadoConsultarFacturasImpagasType
     */
    @WebMethod(operationName = "ConsultarFacturasImpagas", action = "http://www.epcs.com/billing/balance/ConsultarFacturasImpagas")
    @WebResult(name = "ResultadoConsultarFacturasImpagasDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ResultadoConsultarFacturasImpagas")
    public ResultadoConsultarFacturasImpagasType consultarFacturasImpagas(
        @WebParam(name = "ConsultarFacturasImpagasDocument", targetNamespace = "http://www.epcs.com/billing/balance", partName = "ConsultarFacturasImpagas")
        ConsultarFacturasImpagasType consultarFacturasImpagas);

}
