
package com.epcs.billing.pago;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.billing.pago.types.ConsultarEstadoPATType;
import com.epcs.billing.pago.types.ConsultarEstadoPromoPATPACType;
import com.epcs.billing.pago.types.InscribirPATType;
import com.epcs.billing.pago.types.ResultadoConsultarEstadoPATType;
import com.epcs.billing.pago.types.ResultadoConsultarEstadoPromoPATPACType;
import com.epcs.billing.pago.types.ResultadoInscribirPATType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BillingPagoService", targetNamespace = "http://www.epcs.com/billing/pago")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.billing.pago.ObjectFactory.class,
    com.epcs.billing.pago.types.ObjectFactory.class
})
public interface BillingPagoService {


    /**
     * 
     * @param consultarEstadoPAT
     * @return
     *     returns com.epcs.billing.pago.types.ResultadoConsultarEstadoPATType
     */
    @WebMethod(operationName = "ConsultarEstadoPAT", action = "http://www.epcs.com/billing/pago/ConsultarEstadoPAT")
    @WebResult(name = "ResultadoConsultarEstadoPATDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "ResultadoConsultarEstadoPAT")
    public ResultadoConsultarEstadoPATType consultarEstadoPAT(
        @WebParam(name = "ConsultarEstadoPATDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "ConsultarEstadoPAT")
        ConsultarEstadoPATType consultarEstadoPAT);

    /**
     * 
     * @param consultarEstadoPromoPATPAC
     * @return
     *     returns com.epcs.billing.pago.types.ResultadoConsultarEstadoPromoPATPACType
     */
    @WebMethod(operationName = "ConsultarEstadoPromoPATPAC", action = "http://www.epcs.com/billing/pago/ConsultarEstadoPromoPATPAC")
    @WebResult(name = "ResultadoConsultarEstadoPromoPATPACDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "ResultadoConsultarEstadoPromoPATPAC")
    public ResultadoConsultarEstadoPromoPATPACType consultarEstadoPromoPATPAC(
        @WebParam(name = "ConsultarEstadoPromoPATPACDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "ConsultarEstadoPromoPATPAC")
        ConsultarEstadoPromoPATPACType consultarEstadoPromoPATPAC);

    /**
     * 
     * @param inscribirPAT
     * @return
     *     returns com.epcs.billing.pago.types.ResultadoInscribirPATType
     */
    @WebMethod(operationName = "InscribirPAT", action = "http://www.epcs.com/billing/pago/InscribirPAT")
    @WebResult(name = "ResultadoInscribirPATDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "ResultadoInscribirPAT")
    public ResultadoInscribirPATType inscribirPAT(
        @WebParam(name = "InscribirPATDocument", targetNamespace = "http://www.epcs.com/billing/pago", partName = "InscribirPAT")
        InscribirPATType inscribirPAT);

}
