
package com.epcs.provision.suscripcion;

import javax.xml.ws.WebFault;
import com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMServiceFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "listarBolsasActivasBAMServiceFaultDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
public class ListarBolsasActivasBAMServiceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ListarBolsasActivasBAMServiceFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ListarBolsasActivasBAMServiceFaultMessage(String message, ListarBolsasActivasBAMServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ListarBolsasActivasBAMServiceFaultMessage(String message, ListarBolsasActivasBAMServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMServiceFaultType
     */
    public ListarBolsasActivasBAMServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
