
package com.epcs.billing.balance;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BillingBalanceService", targetNamespace = "http://www.epcs.com/billing/balance", wsdlLocation = "BillingBalanceService.wsdl")
public class BillingBalanceService_Service
    extends Service
{

    private final static URL BILLINGBALANCESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epcs.billing.balance.BillingBalanceService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epcs.billing.balance.BillingBalanceService_Service.class.getResource(".");
            url = new URL(baseUrl, "BillingBalanceService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'BillingBalanceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILLINGBALANCESERVICE_WSDL_LOCATION = url;
    }

    public BillingBalanceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingBalanceService_Service() {
        super(BILLINGBALANCESERVICE_WSDL_LOCATION, new QName("http://www.epcs.com/billing/balance", "BillingBalanceService"));
    }

    /**
     * 
     * @return
     *     returns BillingBalanceService
     */
    @WebEndpoint(name = "BillingBalanceServicePort")
    public BillingBalanceService getBillingBalanceServicePort() {
        return super.getPort(new QName("http://www.epcs.com/billing/balance", "BillingBalanceServicePort"), BillingBalanceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingBalanceService
     */
    @WebEndpoint(name = "BillingBalanceServicePort")
    public BillingBalanceService getBillingBalanceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epcs.com/billing/balance", "BillingBalanceServicePort"), BillingBalanceService.class, features);
    }

}
