
package com.epcs.provision.suscripcion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.epcs.provision.suscripcion.types.RequestType;
import com.epcs.provision.suscripcion.types.ResponseCompraType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SCOBPortType", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
@XmlSeeAlso({
    com.epcs.provision.suscripcion.types.ObjectFactory.class,
    com.epcs.provision.suscripcion.ObjectFactory.class
})
public interface SCOBPortType {


    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMResponseType.Mensaje
     * @throws ListarBolsasActivasBAMServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/listarBolsasActivasBAMRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "listarBolsasActivasBAMRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMRequestType")
    @ResponseWrapper(localName = "listarBolsasActivasBAMResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMResponseType")
    public com.epcs.provision.suscripcion.types.ListarBolsasActivasBAMResponseType.Mensaje listarBolsasActivasBAMRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        RequestType mensaje)
        throws ListarBolsasActivasBAMServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMResponseType.Mensaje
     * @throws ListarBolsasDisponiblesBAMServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/listarBolsasDisponiblesBAMRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "listarBolsasDisponiblesBAMRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMRequestType")
    @ResponseWrapper(localName = "listarBolsasDisponiblesBAMResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMResponseType")
    public com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMResponseType.Mensaje listarBolsasDisponiblesBAMRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        RequestType mensaje)
        throws ListarBolsasDisponiblesBAMServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ListarBolsasResponseType.Mensaje
     * @throws ListarBolsasServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/listarBolsasRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "listarBolsasRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasRequestType")
    @ResponseWrapper(localName = "listarBolsasResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasResponseType")
    public com.epcs.provision.suscripcion.types.ListarBolsasResponseType.Mensaje listarBolsasRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        RequestType mensaje)
        throws ListarBolsasServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ResponseCompraType
     * @throws ValidacionCompraServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/validacionCompraRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "validacionCompraRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ValidacionCompraRequestType")
    @ResponseWrapper(localName = "validacionCompraResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ValidacionCompraResponseType")
    public ResponseCompraType validacionCompraRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        com.epcs.provision.suscripcion.types.ValidacionCompraRequestType.Mensaje mensaje)
        throws ValidacionCompraServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ResponseCompraType
     * @throws ValidacionRegaloServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/validacionRegaloRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "validacionRegaloRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ValidacionRegaloRequestType")
    @ResponseWrapper(localName = "validacionRegaloResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ValidacionRegaloResponseType")
    public ResponseCompraType validacionRegaloRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        com.epcs.provision.suscripcion.types.ValidacionRegaloRequestType.Mensaje mensaje)
        throws ValidacionRegaloServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ComprarResponseType.Mensaje
     * @throws ComprarServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/comprarRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "comprarRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ComprarRequestType")
    @ResponseWrapper(localName = "comprarResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ComprarResponseType")
    public com.epcs.provision.suscripcion.types.ComprarResponseType.Mensaje comprarRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        com.epcs.provision.suscripcion.types.ComprarRequestType.Mensaje mensaje)
        throws ComprarServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.RegalarResponseType.Mensaje
     * @throws RegalarServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/regalarRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "regalarRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.RegalarRequestType")
    @ResponseWrapper(localName = "regalarResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.RegalarResponseType")
    public com.epcs.provision.suscripcion.types.RegalarResponseType.Mensaje regalarRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        com.epcs.provision.suscripcion.types.RegalarRequestType.Mensaje mensaje)
        throws RegalarServiceFaultMessage
    ;

    /**
     * 
     * @param mensaje
     * @return
     *     returns com.epcs.provision.suscripcion.types.ListarBolsasActivasResponseType.Mensaje
     * @throws ListarBolsasActivasServiceFaultMessage
     */
    @WebMethod(action = "http://www.epcs.com/Provision/Suscripcion/listarBolsasActivasRequestDocument")
    @WebResult(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
    @RequestWrapper(localName = "listarBolsasActivasRequestDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasActivasRequestType")
    @ResponseWrapper(localName = "listarBolsasActivasResponseDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", className = "com.epcs.provision.suscripcion.types.ListarBolsasActivasResponseType")
    public com.epcs.provision.suscripcion.types.ListarBolsasActivasResponseType.Mensaje listarBolsasActivasRequestDocument(
        @WebParam(name = "mensaje", targetNamespace = "http://www.epcs.com/Provision/Suscripcion/types")
        com.epcs.provision.suscripcion.types.ListarBolsasActivasRequestType.Mensaje mensaje)
        throws ListarBolsasActivasServiceFaultMessage
    ;

}
