
package com.epcs.cliente.perfil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.cliente.perfil.types.ActualizarMisDatosType;
import com.epcs.cliente.perfil.types.ConsultarAutoatencionType;
import com.epcs.cliente.perfil.types.ConsultarBolsaActualType;
import com.epcs.cliente.perfil.types.ConsultarBolsasCompradasType;
import com.epcs.cliente.perfil.types.ConsultarCiudadesPorRegionType;
import com.epcs.cliente.perfil.types.ConsultarComunasPorCiudadType;
import com.epcs.cliente.perfil.types.ConsultarEquipoType;
import com.epcs.cliente.perfil.types.ConsultarMisDatosType;
import com.epcs.cliente.perfil.types.ConsultarMisUsuariosType;
import com.epcs.cliente.perfil.types.ConsultarPerfilamientoType;
import com.epcs.cliente.perfil.types.ConsultarPlanContratadoPPType;
import com.epcs.cliente.perfil.types.ConsultarPlanResumenCCType;
import com.epcs.cliente.perfil.types.ConsultarPlanResumenPPType;
import com.epcs.cliente.perfil.types.ConsultarPlanType;
import com.epcs.cliente.perfil.types.ConsultarProductosType;
import com.epcs.cliente.perfil.types.ConsultarRegionesType;
import com.epcs.cliente.perfil.types.ConsultarSelectorCuentaType;
import com.epcs.cliente.perfil.types.ResultadoActualizarMisDatosType;
import com.epcs.cliente.perfil.types.ResultadoConsultarAutoatencionType;
import com.epcs.cliente.perfil.types.ResultadoConsultarBolsaActualType;
import com.epcs.cliente.perfil.types.ResultadoConsultarBolsasCompradasType;
import com.epcs.cliente.perfil.types.ResultadoConsultarCiudadesPorRegionType;
import com.epcs.cliente.perfil.types.ResultadoConsultarComunasPorCiudadType;
import com.epcs.cliente.perfil.types.ResultadoConsultarEquipoType;
import com.epcs.cliente.perfil.types.ResultadoConsultarMisDatosType;
import com.epcs.cliente.perfil.types.ResultadoConsultarMisUsuariosType;
import com.epcs.cliente.perfil.types.ResultadoConsultarPerfilamientoType;
import com.epcs.cliente.perfil.types.ResultadoConsultarPlanContratadoPPType;
import com.epcs.cliente.perfil.types.ResultadoConsultarPlanResumenCCType;
import com.epcs.cliente.perfil.types.ResultadoConsultarPlanResumenPPType;
import com.epcs.cliente.perfil.types.ResultadoConsultarPlanType;
import com.epcs.cliente.perfil.types.ResultadoConsultarProductosType;
import com.epcs.cliente.perfil.types.ResultadoConsultarRegionesType;
import com.epcs.cliente.perfil.types.ResultadoConsultarSelectorCuentaType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClientePerfilServicePortType", targetNamespace = "http://www.epcs.com/cliente/perfil")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.cliente.perfil.ObjectFactory.class,
    com.epcs.cliente.perfil.types.ObjectFactory.class
})
public interface ClientePerfilServicePortType {


    /**
     * 
     * @param consultarProductos
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarProductosType
     */
    @WebMethod(operationName = "ConsultarProductos", action = "http://www.epcs.com/cliente/perfil/ConsultarProductos")
    @WebResult(name = "ResultadoConsultarProductosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarProductos")
    public ResultadoConsultarProductosType consultarProductos(
        @WebParam(name = "ConsultarProductosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarProductos")
        ConsultarProductosType consultarProductos);

    /**
     * 
     * @param consultarPlan
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarPlanType
     */
    @WebMethod(operationName = "ConsultarPlan", action = "http://www.epcs.com/cliente/perfil/ConsultarPlan")
    @WebResult(name = "ResultadoConsultarPlanDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPlan")
    public ResultadoConsultarPlanType consultarPlan(
        @WebParam(name = "ConsultarPlanDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarPlan")
        ConsultarPlanType consultarPlan);

    /**
     * 
     * @param consultarBolsaActual
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarBolsaActualType
     */
    @WebMethod(operationName = "ConsultarBolsaActual", action = "http://www.epcs.com/cliente/perfil/ConsultarBolsaActual")
    @WebResult(name = "ResultadoConsultarBolsaActualDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarBolsaActual")
    public ResultadoConsultarBolsaActualType consultarBolsaActual(
        @WebParam(name = "ConsultarBolsaActualDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarBolsaActual")
        ConsultarBolsaActualType consultarBolsaActual);

    /**
     * 
     * @param consultarEquipo
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarEquipoType
     */
    @WebMethod(operationName = "ConsultarEquipo", action = "http://www.epcs.com/cliente/perfil/ConsultarEquipo")
    @WebResult(name = "ResultadoConsultarEquipoDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarEquipo")
    public ResultadoConsultarEquipoType consultarEquipo(
        @WebParam(name = "ConsultarEquipoDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarEquipo")
        ConsultarEquipoType consultarEquipo);

    /**
     * 
     * @param consultarPerfilamiento
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarPerfilamientoType
     */
    @WebMethod(operationName = "ConsultarPerfilamiento", action = "http://www.epcs.com/cliente/perfil/ConsultarPerfilamiento")
    @WebResult(name = "ResultadoConsultarPerfilamientoDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPerfilamiento")
    public ResultadoConsultarPerfilamientoType consultarPerfilamiento(
        @WebParam(name = "ConsultarPerfilamientoDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarPerfilamiento")
        ConsultarPerfilamientoType consultarPerfilamiento);

    /**
     * 
     * @param consultarPlanContratadoPP
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarPlanContratadoPPType
     */
    @WebMethod(operationName = "ConsultarPlanContratadoPP", action = "http://www.epcs.com/cliente/perfil/ConsultarPlanContratadoPP")
    @WebResult(name = "ResultadoConsultarPlanContratadoPPDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPlanContratadoPP")
    public ResultadoConsultarPlanContratadoPPType consultarPlanContratadoPP(
        @WebParam(name = "ConsultarPlanContratadoPPDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarPlanContratadoPP")
        ConsultarPlanContratadoPPType consultarPlanContratadoPP);

    /**
     * 
     * @param resultadoConsultarPlanResumenCC
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarPlanResumenCCType
     */
    @WebMethod(operationName = "ConsultarPlanResumenCC", action = "http://www.epcs.com/cliente/perfil/ConsultarPlanResumenCC")
    @WebResult(name = "ResultadoConsultarPlanResumenCCDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPlanResumenCC")
    public ResultadoConsultarPlanResumenCCType consultarPlanResumenCC(
        @WebParam(name = "ConsultarPlanResumenCCDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPlanResumenCC")
        ConsultarPlanResumenCCType resultadoConsultarPlanResumenCC);

    /**
     * 
     * @param consultarPlanResumenPP
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarPlanResumenPPType
     */
    @WebMethod(operationName = "ConsultarPlanResumenPP", action = "http://www.epcs.com/cliente/perfil/ConsultarPlanResumenPP")
    @WebResult(name = "ResultadoConsultarPlanResumenPPDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarPlanResumenPP")
    public ResultadoConsultarPlanResumenPPType consultarPlanResumenPP(
        @WebParam(name = "ConsultarPlanResumenPPDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarPlanResumenPP")
        ConsultarPlanResumenPPType consultarPlanResumenPP);

    /**
     * 
     * @param consultarMisDatos
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarMisDatosType
     */
    @WebMethod(operationName = "ConsultarMisDatos", action = "http://www.epcs.com/cliente/perfil/ConsultarMisDatos")
    @WebResult(name = "ResultadoConsultarMisDatosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarMisDatos")
    public ResultadoConsultarMisDatosType consultarMisDatos(
        @WebParam(name = "ConsultarMisDatosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarMisDatos")
        ConsultarMisDatosType consultarMisDatos);

    /**
     * 
     * @param actualizarMisDatos
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoActualizarMisDatosType
     */
    @WebMethod(operationName = "ActualizarMisDatos", action = "http://www.epcs.com/cliente/perfil/ActualizarMisDatos")
    @WebResult(name = "ResultadoActualizarMisDatosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoActualizarMisDatos")
    public ResultadoActualizarMisDatosType actualizarMisDatos(
        @WebParam(name = "ActualizarMisDatosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ActualizarMisDatos")
        ActualizarMisDatosType actualizarMisDatos);

    /**
     * 
     * @param consultarMisUsuarios
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarMisUsuariosType
     */
    @WebMethod(operationName = "ConsultarMisUsuarios", action = "http://www.epcs.com/cliente/perfil/ConsultarMisUsuarios")
    @WebResult(name = "ResultadoConsultarMisUsuariosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarMisUsuarios")
    public ResultadoConsultarMisUsuariosType consultarMisUsuarios(
        @WebParam(name = "ConsultarMisUsuariosDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarMisUsuarios")
        ConsultarMisUsuariosType consultarMisUsuarios);

    /**
     * 
     * @param consultarSelectorCuenta
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarSelectorCuentaType
     */
    @WebMethod(operationName = "ConsultarSelectorCuenta", action = "http://www.epcs.com/cliente/perfil/ConsultarSelectorCuenta")
    @WebResult(name = "ResultadoConsultarSelectorCuentaDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarSelectorCuenta")
    public ResultadoConsultarSelectorCuentaType consultarSelectorCuenta(
        @WebParam(name = "ConsultarSelectorCuentaDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarSelectorCuenta")
        ConsultarSelectorCuentaType consultarSelectorCuenta);

    /**
     * 
     * @param consultarAutoatencion
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarAutoatencionType
     */
    @WebMethod(operationName = "ConsultarAutoatencion", action = "http://www.epcs.com/cliente/perfil/ConsultarAutoatencion")
    @WebResult(name = "ResultadoConsultarAutoatencionDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoAutoatencion")
    public ResultadoConsultarAutoatencionType consultarAutoatencion(
        @WebParam(name = "ConsultarAutoatencionDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarAutoatencion")
        ConsultarAutoatencionType consultarAutoatencion);

    /**
     * 
     * @param consultarBolsasCompradas
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarBolsasCompradasType
     */
    @WebMethod(operationName = "ConsultarBolsasCompradas", action = "http://www.epcs.com/cliente/perfil/ConsultarBolsasCompradas")
    @WebResult(name = "ResultadoConsultarBolsasCompradasDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoBolsasCompradas")
    public ResultadoConsultarBolsasCompradasType consultarBolsasCompradas(
        @WebParam(name = "ConsultarBolsasCompradasDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarBolsasCompradas")
        ConsultarBolsasCompradasType consultarBolsasCompradas);

    /**
     * 
     * @param consultarCiudadesPorRegion
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarCiudadesPorRegionType
     */
    @WebMethod(operationName = "ConsultarCiudadesPorRegion", action = "http://www.epcs.com/cliente/perfil/ConsultarCiudadesPorRegion")
    @WebResult(name = "ResultadoConsultarCiudadesPorRegionDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarCiudadesPorRegion")
    public ResultadoConsultarCiudadesPorRegionType consultarCiudadesPorRegion(
        @WebParam(name = "ConsultarCiudadesPorRegionDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarCiudadesPorRegion")
        ConsultarCiudadesPorRegionType consultarCiudadesPorRegion);

    /**
     * 
     * @param consultarComunasPorCiudad
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarComunasPorCiudadType
     */
    @WebMethod(operationName = "ConsultarComunasPorCiudad", action = "http://www.epcs.com/cliente/perfil/ConsultarComunasPorCiudad")
    @WebResult(name = "ResultadoConsultarComunasPorCiudadDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarComunasPorCiudad")
    public ResultadoConsultarComunasPorCiudadType consultarComunasPorCiudad(
        @WebParam(name = "ConsultarComunasPorCiudadDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarComunasPorCiudad")
        ConsultarComunasPorCiudadType consultarComunasPorCiudad);

    /**
     * 
     * @param consultarRegiones
     * @return
     *     returns com.epcs.cliente.perfil.types.ResultadoConsultarRegionesType
     */
    @WebMethod(operationName = "ConsultarRegiones", action = "http://www.epcs.com/cliente/perfil/ConsultarRegiones")
    @WebResult(name = "ResultadoConsultarRegionesDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ResultadoConsultarRegiones")
    public ResultadoConsultarRegionesType consultarRegiones(
        @WebParam(name = "ConsultarRegionesDocument", targetNamespace = "http://www.epcs.com/cliente/perfil", partName = "ConsultarRegiones")
        ConsultarRegionesType consultarRegiones);

}
