
package com.epcs.provision.suscripcion;

import javax.xml.ws.WebFault;
import com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMServiceFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "listarBolsasDisponiblesBAMServiceFaultDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
public class ListarBolsasDisponiblesBAMServiceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ListarBolsasDisponiblesBAMServiceFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ListarBolsasDisponiblesBAMServiceFaultMessage(String message, ListarBolsasDisponiblesBAMServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ListarBolsasDisponiblesBAMServiceFaultMessage(String message, ListarBolsasDisponiblesBAMServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epcs.provision.suscripcion.types.ListarBolsasDisponiblesBAMServiceFaultType
     */
    public ListarBolsasDisponiblesBAMServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
