
package com.epcs.inteligencianegocios.satisfaccioncliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.inteligencianegocios.satisfaccioncliente.types.ConsultarEncuestasPerfiladasOrqType;
import com.epcs.inteligencianegocios.satisfaccioncliente.types.ConsultarEncuestasPerfiladasType;
import com.epcs.inteligencianegocios.satisfaccioncliente.types.ResultadoConsultarEncuestasPerfiladasOrqType;
import com.epcs.inteligencianegocios.satisfaccioncliente.types.ResultadoConsultarEncuestasPerfiladasType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SatisfaccionClienteServicePortType", targetNamespace = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.inteligencianegocios.satisfaccioncliente.types.ObjectFactory.class,
    com.epcs.inteligencianegocios.satisfaccioncliente.ObjectFactory.class
})
public interface SatisfaccionClienteServicePortType {


    /**
     * 
     * @param consultarEncuestasPerfiladas
     * @return
     *     returns com.epcs.inteligencianegocios.satisfaccioncliente.types.ResultadoConsultarEncuestasPerfiladasType
     */
    @WebMethod(operationName = "ConsultarEncuestasPerfiladas", action = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente/ConsultarEncuestasPerfiladas")
    @WebResult(name = "ResultadoConsultarEncuestasPerfiladasDocument", targetNamespace = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente", partName = "ResultadoConsultarEncuestasPerfiladas")
    public ResultadoConsultarEncuestasPerfiladasType consultarEncuestasPerfiladas(
        @WebParam(name = "ConsultarEncuestasPerfiladasDocument", targetNamespace = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente", partName = "ConsultarEncuestasPerfiladas")
        ConsultarEncuestasPerfiladasType consultarEncuestasPerfiladas);

    /**
     * 
     * @param consultarEncuestasPerfiladasOrq
     * @return
     *     returns com.epcs.inteligencianegocios.satisfaccioncliente.types.ResultadoConsultarEncuestasPerfiladasOrqType
     */
    @WebMethod(operationName = "ConsultarEncuestasPerfiladasOrq", action = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente/ConsultarEncuestasPerfiladasOrq")
    @WebResult(name = "ResultadoConsultarEncuestasPerfiladasOrqDocument", targetNamespace = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente", partName = "ResultadoConsultarEncuestasPerfiladasOrq")
    public ResultadoConsultarEncuestasPerfiladasOrqType consultarEncuestasPerfiladasOrq(
        @WebParam(name = "ConsultarEncuestasPerfiladasOrqDocument", targetNamespace = "http://www.epcs.com/inteligencianegocios/satisfaccioncliente", partName = "ConsultarEncuestasPerfiladasOrq")
        ConsultarEncuestasPerfiladasOrqType consultarEncuestasPerfiladasOrq);

}
