
package com.epcs.provision.suscripcion;

import javax.xml.ws.WebFault;
import com.epcs.provision.suscripcion.types.RegalarServiceFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "regalarServiceFaultDocument", targetNamespace = "http://www.epcs.com/Provision/Suscripcion")
public class RegalarServiceFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RegalarServiceFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RegalarServiceFaultMessage(String message, RegalarServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RegalarServiceFaultMessage(String message, RegalarServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epcs.provision.suscripcion.types.RegalarServiceFaultType
     */
    public RegalarServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
