
package com.epcs.billing.plan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.billing.plan.types.AdministrarNumeroFrecuenteSSType;
import com.epcs.billing.plan.types.AgregarModificarNumeroFrecuentePPType;
import com.epcs.billing.plan.types.CambioPlanComunik2PPType;
import com.epcs.billing.plan.types.CambioPlanPPType;
import com.epcs.billing.plan.types.CambioPlanSSCCType;
import com.epcs.billing.plan.types.ConsultarNumeroFrecuenteCCType;
import com.epcs.billing.plan.types.ConsultarNumeroFrecuenteSSType;
import com.epcs.billing.plan.types.ConsultarPlanActualCCType;
import com.epcs.billing.plan.types.ConsultarPlanActualPPType;
import com.epcs.billing.plan.types.ConsultarPlanActualSSType;
import com.epcs.billing.plan.types.ConsultarPlanesDisponiblesPPType;
import com.epcs.billing.plan.types.ConsultarPlanesDisponiblesSSCCType;
import com.epcs.billing.plan.types.ConsultarSolicitudesActivasPPType;
import com.epcs.billing.plan.types.EliminarNumeroFrecuentePPType;
import com.epcs.billing.plan.types.ResultadoAdministrarNumeroFrecuenteSSType;
import com.epcs.billing.plan.types.ResultadoAgregarModificarNumeroFrecuentePPType;
import com.epcs.billing.plan.types.ResultadoCambioPlanComunik2PPType;
import com.epcs.billing.plan.types.ResultadoCambioPlanPPType;
import com.epcs.billing.plan.types.ResultadoCambioPlanSSCCType;
import com.epcs.billing.plan.types.ResultadoConsultarNumeroFrecuenteCCType;
import com.epcs.billing.plan.types.ResultadoConsultarNumeroFrecuenteSSType;
import com.epcs.billing.plan.types.ResultadoConsultarPlanActualCCType;
import com.epcs.billing.plan.types.ResultadoConsultarPlanActualPPType;
import com.epcs.billing.plan.types.ResultadoConsultarPlanActualSSType;
import com.epcs.billing.plan.types.ResultadoConsultarPlanesDisponiblesPPType;
import com.epcs.billing.plan.types.ResultadoConsultarPlanesDisponiblesSSCCType;
import com.epcs.billing.plan.types.ResultadoConsultarSolicitudesActivasPPType;
import com.epcs.billing.plan.types.ResultadoEliminarNumeroFrecuentePPType;
import com.epcs.billing.plan.types.ResultadoValidacionBloqueoTemporalType;
import com.epcs.billing.plan.types.ResultadoValidacionComercialType;
import com.epcs.billing.plan.types.ValidacionBloqueoTemporalType;
import com.epcs.billing.plan.types.ValidacionComercialType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BillingPlanService", targetNamespace = "http://www.epcs.com/billing/plan")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.billing.plan.ObjectFactory.class,
    com.epcs.billing.plan.types.ObjectFactory.class
})
public interface BillingPlanService {


    /**
     * 
     * @param consultarPlanActualSS
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarPlanActualSSType
     */
    @WebMethod(operationName = "ConsultarPlanActualSS", action = "http://www.epcs.com/billing/plan/ConsultarPlanActualSS")
    @WebResult(name = "ResultadoConsultarPlanActualSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarPlanActualSS")
    public ResultadoConsultarPlanActualSSType consultarPlanActualSS(
        @WebParam(name = "ConsultarPlanActualSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarPlanActualSS")
        ConsultarPlanActualSSType consultarPlanActualSS);

    /**
     * 
     * @param consultarPlanActualCC
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarPlanActualCCType
     */
    @WebMethod(operationName = "ConsultarPlanActualCC", action = "http://www.epcs.com/billing/plan/ConsultarPlanActualCC")
    @WebResult(name = "ResultadoConsultarPlanActualCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarPlanActualCC")
    public ResultadoConsultarPlanActualCCType consultarPlanActualCC(
        @WebParam(name = "ConsultarPlanActualCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarPlanActualCC")
        ConsultarPlanActualCCType consultarPlanActualCC);

    /**
     * 
     * @param consultarPlanActualPP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarPlanActualPPType
     */
    @WebMethod(operationName = "ConsultarPlanActualPP", action = "http://www.epcs.com/billing/plan/ConsultarPlanActualPP")
    @WebResult(name = "ResultadoConsultarPlanActualPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarPlanActualPP")
    public ResultadoConsultarPlanActualPPType consultarPlanActualPP(
        @WebParam(name = "ConsultarPlanActualPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarPlanActualPP")
        ConsultarPlanActualPPType consultarPlanActualPP);

    /**
     * 
     * @param consultarSolicitudesActivasPP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarSolicitudesActivasPPType
     */
    @WebMethod(operationName = "ConsultarSolicitudesActivasPP", action = "http://www.epcs.com/billing/plan/ConsultarSolicitudesActivasPP")
    @WebResult(name = "ResultadoConsultarSolicitudesActivasPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarSolicitudesActivasPP")
    public ResultadoConsultarSolicitudesActivasPPType consultarSolicitudesActivasPP(
        @WebParam(name = "ConsultarSolicitudesActivasPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarSolicitudesActivasPP")
        ConsultarSolicitudesActivasPPType consultarSolicitudesActivasPP);

    /**
     * 
     * @param cambioPlanPP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoCambioPlanPPType
     */
    @WebMethod(operationName = "CambioPlanPP", action = "http://www.epcs.com/billing/plan/CambioPlanPP")
    @WebResult(name = "ResultadoCambioPlanPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoCambioPlanPP")
    public ResultadoCambioPlanPPType cambioPlanPP(
        @WebParam(name = "CambioPlanPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "CambioPlanPP")
        CambioPlanPPType cambioPlanPP);

    /**
     * 
     * @param cambioPlanComunik2PP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoCambioPlanComunik2PPType
     */
    @WebMethod(operationName = "CambioPlanComunik2PP", action = "http://www.epcs.com/billing/plan/CambioPlanComunik2PP")
    @WebResult(name = "ResultadoCambioPlanComunik2PPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoCambioPlanComunik2PP")
    public ResultadoCambioPlanComunik2PPType cambioPlanComunik2PP(
        @WebParam(name = "CambioPlanComunik2PPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "CambioPlanComunik2PP")
        CambioPlanComunik2PPType cambioPlanComunik2PP);

    /**
     * 
     * @param agregarModificarNumeroFrecuentePP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoAgregarModificarNumeroFrecuentePPType
     */
    @WebMethod(operationName = "AgregarModificarNumeroFrecuentePP", action = "http://www.epcs.com/billing/plan/AgregarModificarNumeroFrecuentePP")
    @WebResult(name = "ResultadoAgregarModificarNumeroFrecuentePPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoAgregarModificarNumeroFrecuentePP")
    public ResultadoAgregarModificarNumeroFrecuentePPType agregarModificarNumeroFrecuentePP(
        @WebParam(name = "AgregarModificarNumeroFrecuentePPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "AgregarModificarNumeroFrecuentePP")
        AgregarModificarNumeroFrecuentePPType agregarModificarNumeroFrecuentePP);

    /**
     * 
     * @param eliminarNumeroFrecuentePP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoEliminarNumeroFrecuentePPType
     */
    @WebMethod(operationName = "EliminarNumeroFrecuentePP", action = "http://www.epcs.com/billing/plan/EliminarNumeroFrecuentePP")
    @WebResult(name = "ResultadoEliminarNumeroFrecuentePPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoEliminarNumeroFrecuentePP")
    public ResultadoEliminarNumeroFrecuentePPType eliminarNumeroFrecuentePP(
        @WebParam(name = "EliminarNumeroFrecuentePPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "EliminarNumeroFrecuentePP")
        EliminarNumeroFrecuentePPType eliminarNumeroFrecuentePP);

    /**
     * 
     * @param consultarPlanesDisponiblesSSCC
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarPlanesDisponiblesSSCCType
     */
    @WebMethod(operationName = "ConsultarPlanesDisponiblesSSCC", action = "http://www.epcs.com/billing/plan/ConsultarPlanesDisponiblesSSCC")
    @WebResult(name = "ResultadoConsultarPlanesDisponiblesSSCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarPlanesDisponiblesSSCC")
    public ResultadoConsultarPlanesDisponiblesSSCCType consultarPlanesDisponiblesSSCC(
        @WebParam(name = "ConsultarPlanesDisponiblesSSCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarPlanesDisponiblesSSCC")
        ConsultarPlanesDisponiblesSSCCType consultarPlanesDisponiblesSSCC);

    /**
     * 
     * @param consultarPlanesDisponiblesPP
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarPlanesDisponiblesPPType
     */
    @WebMethod(operationName = "ConsultarPlanesDisponiblesPP", action = "http://www.epcs.com/billing/plan/ConsultarPlanesDisponiblesPP")
    @WebResult(name = "ResultadoConsultarPlanesDisponiblesPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarPlanesDisponiblesPP")
    public ResultadoConsultarPlanesDisponiblesPPType consultarPlanesDisponiblesPP(
        @WebParam(name = "ConsultarPlanesDisponiblesPPDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarPlanesDisponiblesPP")
        ConsultarPlanesDisponiblesPPType consultarPlanesDisponiblesPP);

    /**
     * 
     * @param validacionBloqueoTemporal
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoValidacionBloqueoTemporalType
     */
    @WebMethod(operationName = "ValidacionBloqueoTemporal", action = "http://www.epcs.com/billing/plan/ValidacionBloqueoTemporal")
    @WebResult(name = "ResultadoValidacionBloqueoTemporalDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoValidacionBloqueoTemporal")
    public ResultadoValidacionBloqueoTemporalType validacionBloqueoTemporal(
        @WebParam(name = "ValidacionBloqueoTemporalDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ValidacionBloqueoTemporal")
        ValidacionBloqueoTemporalType validacionBloqueoTemporal);

    /**
     * 
     * @param validacionComercial
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoValidacionComercialType
     */
    @WebMethod(operationName = "ValidacionComercial", action = "http://www.epcs.com/billing/plan/ValidacionComercial")
    @WebResult(name = "ResultadoValidacionComercialDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoValidacionComercial")
    public ResultadoValidacionComercialType validacionComercial(
        @WebParam(name = "ValidacionComercialDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ValidacionComercial")
        ValidacionComercialType validacionComercial);

    /**
     * 
     * @param cambioPlanSSCC
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoCambioPlanSSCCType
     */
    @WebMethod(operationName = "CambioPlanSSCC", action = "http://www.epcs.com/billing/plan/CambioPlanSSCC")
    @WebResult(name = "ResultadoCambioPlanSSCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoCambioPlanSSCC")
    public ResultadoCambioPlanSSCCType cambioPlanSSCC(
        @WebParam(name = "CambioPlanSSCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "CambioPlanSSCC")
        CambioPlanSSCCType cambioPlanSSCC);

    /**
     * 
     * @param consultarNumeroFrecuenteSS
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarNumeroFrecuenteSSType
     */
    @WebMethod(operationName = "ConsultarNumeroFrecuenteSS", action = "http://www.epcs.com/billing/plan/ConsultarNumeroFrecuenteSS")
    @WebResult(name = "ResultadoConsultarNumeroFrecuenteSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarNumeroFrecuenteSS")
    public ResultadoConsultarNumeroFrecuenteSSType consultarNumeroFrecuenteSS(
        @WebParam(name = "ConsultarNumeroFrecuenteSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarNumeroFrecuenteSS")
        ConsultarNumeroFrecuenteSSType consultarNumeroFrecuenteSS);

    /**
     * 
     * @param consultarNumeroFrecuenteCC
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoConsultarNumeroFrecuenteCCType
     */
    @WebMethod(operationName = "ConsultarNumeroFrecuenteCC", action = "http://www.epcs.com/billing/plan/ConsultarNumeroFrecuenteCC")
    @WebResult(name = "ResultadoConsultarNumeroFrecuenteCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoConsultarNumeroFrecuenteCC")
    public ResultadoConsultarNumeroFrecuenteCCType consultarNumeroFrecuenteCC(
        @WebParam(name = "ConsultarNumeroFrecuenteCCDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ConsultarNumeroFrecuenteCC")
        ConsultarNumeroFrecuenteCCType consultarNumeroFrecuenteCC);

    /**
     * 
     * @param administrarNumeroFrecuenteSS
     * @return
     *     returns com.epcs.billing.plan.types.ResultadoAdministrarNumeroFrecuenteSSType
     */
    @WebMethod(operationName = "AdministrarNumeroFrecuenteSS", action = "http://www.epcs.com/billing/plan/AdministrarNumeroFrecuenteSS")
    @WebResult(name = "ResultadoAdministrarNumeroFrecuenteSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "ResultadoAdministrarNumeroFrecuenteSS")
    public ResultadoAdministrarNumeroFrecuenteSSType administrarNumeroFrecuenteSS(
        @WebParam(name = "AdministrarNumeroFrecuenteSSDocument", targetNamespace = "http://www.epcs.com/billing/plan", partName = "AdministrarNumeroFrecuenteSS")
        AdministrarNumeroFrecuenteSSType administrarNumeroFrecuenteSS);

}
