
package com.epcs.provision.suscripcion;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SCOBPortTypeSOAPBindingQSService", targetNamespace = "http://www.epcs.com/Provision/Suscripcion", wsdlLocation = "BolsasPPService.wsdl")
public class SCOBPortTypeSOAPBindingQSService
    extends Service
{

    private final static URL SCOBPORTTYPESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epcs.provision.suscripcion.SCOBPortTypeSOAPBindingQSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epcs.provision.suscripcion.SCOBPortTypeSOAPBindingQSService.class.getResource(".");
            url = new URL(baseUrl, "BolsasPPService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'BolsasPPService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SCOBPORTTYPESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
    }

    public SCOBPortTypeSOAPBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SCOBPortTypeSOAPBindingQSService() {
        super(SCOBPORTTYPESOAPBINDINGQSSERVICE_WSDL_LOCATION, new QName("http://www.epcs.com/Provision/Suscripcion", "SCOBPortTypeSOAPBindingQSService"));
    }

    /**
     * 
     * @return
     *     returns SCOBPortType
     */
    @WebEndpoint(name = "SCOBPortTypeSOAPBindingQSPort")
    public SCOBPortType getSCOBPortTypeSOAPBindingQSPort() {
        return super.getPort(new QName("http://www.epcs.com/Provision/Suscripcion", "SCOBPortTypeSOAPBindingQSPort"), SCOBPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SCOBPortType
     */
    @WebEndpoint(name = "SCOBPortTypeSOAPBindingQSPort")
    public SCOBPortType getSCOBPortTypeSOAPBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epcs.com/Provision/Suscripcion", "SCOBPortTypeSOAPBindingQSPort"), SCOBPortType.class, features);
    }

}
