
package com.esa.clientes.perfilesclientes.sgacarterasvip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.esa.clientes.perfilesclientes.sgacarterasvip.types.EntradaConsultaEjecutivo;
import com.esa.clientes.perfilesclientes.sgacarterasvip.types.SalidaConsultaEjecutivoType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSConsultaEjecutivoPorANIPortType", targetNamespace = "http://www.esa.com/Clientes/PerfilesClientes/SGACarterasVIP")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.esa.clientes.perfilesclientes.sgacarterasvip.ObjectFactory.class,
    com.esa.clientes.perfilesclientes.sgacarterasvip.types.ObjectFactory.class
})
public interface WSConsultaEjecutivoPorANIPortType {


    /**
     * 
     * @param consultaEjecutivoRequest
     * @return
     *     returns com.esa.clientes.perfilesclientes.sgacarterasvip.types.SalidaConsultaEjecutivoType
     * @throws ConsultaEjecutivoFault
     */
    @WebMethod(operationName = "ConsultaEjecutivo", action = "http://www.esa.com/Clientes/PerfilesClientes/SGACarterasVIP/ConsultaEjecutivo")
    @WebResult(name = "ConsultaEjecutivoResponseDocument", targetNamespace = "http://www.esa.com/Clientes/PerfilesClientes/SGACarterasVIP", partName = "ConsultaEjecutivoResponse")
    public SalidaConsultaEjecutivoType consultaEjecutivo(
        @WebParam(name = "ConsultaEjecutivoRequestDocument", targetNamespace = "http://www.esa.com/Clientes/PerfilesClientes/SGACarterasVIP", partName = "ConsultaEjecutivoRequest")
        EntradaConsultaEjecutivo consultaEjecutivoRequest)
        throws ConsultaEjecutivoFault
    ;

}
