
package com.epcs.billing.recarga;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BillingRecargaService", targetNamespace = "http://www.epcs.com/billing/recarga", wsdlLocation = "BillingRecargaService.wsdl")
public class BillingRecargaService
    extends Service
{

    private final static URL BILLINGRECARGASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.epcs.billing.recarga.BillingRecargaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.epcs.billing.recarga.BillingRecargaService.class.getResource(".");
            url = new URL(baseUrl, "BillingRecargaService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'BillingRecargaService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILLINGRECARGASERVICE_WSDL_LOCATION = url;
    }

    public BillingRecargaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingRecargaService() {
        super(BILLINGRECARGASERVICE_WSDL_LOCATION, new QName("http://www.epcs.com/billing/recarga", "BillingRecargaService"));
    }

    /**
     * 
     * @return
     *     returns BillingRecargaServicePortType
     */
    @WebEndpoint(name = "BillingRecargaServicePort")
    public BillingRecargaServicePortType getBillingRecargaServicePort() {
        return super.getPort(new QName("http://www.epcs.com/billing/recarga", "BillingRecargaServicePort"), BillingRecargaServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingRecargaServicePortType
     */
    @WebEndpoint(name = "BillingRecargaServicePort")
    public BillingRecargaServicePortType getBillingRecargaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.epcs.com/billing/recarga", "BillingRecargaServicePort"), BillingRecargaServicePortType.class, features);
    }

}
