
package com.epcs.cliente.orden;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epcs.cliente.orden.types.ConsultarEstadoReposicionType;
import com.epcs.cliente.orden.types.ConsultarValidarReposicionType;
import com.epcs.cliente.orden.types.ReposicionServicioMQType;
import com.epcs.cliente.orden.types.ReposicionServicioOrqType;
import com.epcs.cliente.orden.types.ResultadoConsultarEstadoReposicionType;
import com.epcs.cliente.orden.types.ResultadoReposicionServicioMQType;
import com.epcs.cliente.orden.types.ResultadoReposicionServicioOrqType;
import com.epcs.cliente.orden.types.ResultadoValidarReposicionType;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClienteOrdenService", targetNamespace = "http://www.epcs.com/cliente/orden")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.epcs.cliente.orden.ObjectFactory.class,
    com.epcs.cliente.orden.types.ObjectFactory.class
})
public interface ClienteOrdenService {


    /**
     * 
     * @param consultarEstadoReposicion
     * @return
     *     returns com.epcs.cliente.orden.types.ResultadoConsultarEstadoReposicionType
     */
    @WebMethod(operationName = "ConsultarEstadoReposicion", action = "http://www.epcs.com/cliente/orden/ConsultarEstadoReposicion")
    @WebResult(name = "ResultadoConsultarEstadoReposicionDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ResultadoConsultarEstadoReposicion")
    public ResultadoConsultarEstadoReposicionType consultarEstadoReposicion(
        @WebParam(name = "ConsultarEstadoReposicionDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ConsultarEstadoReposicion")
        ConsultarEstadoReposicionType consultarEstadoReposicion);

    /**
     * 
     * @param consultarValidarReposicion
     * @return
     *     returns com.epcs.cliente.orden.types.ResultadoValidarReposicionType
     */
    @WebMethod(operationName = "ValidarReposicion", action = "http://www.epcs.com/cliente/orden/ValidarReposicion")
    @WebResult(name = "ResultadoValidarReposicionDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ResultadoValidarReposicion")
    public ResultadoValidarReposicionType validarReposicion(
        @WebParam(name = "ConsultarValidarReposicionDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ConsultarValidarReposicion")
        ConsultarValidarReposicionType consultarValidarReposicion);

    /**
     * 
     * @param reposicionServicioMQ
     * @return
     *     returns com.epcs.cliente.orden.types.ResultadoReposicionServicioMQType
     */
    @WebMethod(operationName = "ReposicionServicioMQ", action = "http://www.epcs.com/cliente/orden/ReposicionServicioMQ")
    @WebResult(name = "ResultadoReposicionServicioMQDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ResultadoReposicionServicioMQ")
    public ResultadoReposicionServicioMQType reposicionServicioMQ(
        @WebParam(name = "ReposicionServicioMQDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ReposicionServicioMQ")
        ReposicionServicioMQType reposicionServicioMQ);

    /**
     * 
     * @param reposicionServicioOrq
     * @return
     *     returns com.epcs.cliente.orden.types.ResultadoReposicionServicioOrqType
     */
    @WebMethod(operationName = "ReposicionServicioOrq", action = "http://www.epcs.com/cliente/orden/ReposicionServicioOrq")
    @WebResult(name = "ResultadoReposicionServicioOrqDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ResultadoReposicionServicioOrq")
    public ResultadoReposicionServicioOrqType reposicionServicioOrq(
        @WebParam(name = "ReposicionServicioOrqDocument", targetNamespace = "http://www.epcs.com/cliente/orden", partName = "ReposicionServicioOrq")
        ReposicionServicioOrqType reposicionServicioOrq);

}
